name: wordwolf
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0+4

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1
  json_annotation: ^4.8.1
  flutter_launcher_icons: ^0.13.1
  peerdart: ^0.5.3
  sensors_plus: ^3.0.3
  flutter_webrtc: ^0.9.42+hotfix.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  json_serializable: ^6.7.0

flutter:

  fonts:
     - family: zen
       fonts:
         - asset: assets/fonts/ZenOldMincho-Medium.ttf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"